### ISSUE TITLE
Select range for paired brackets on double click

### ISSUE THREAD

**Issue by izuzak** [atom/bracket-matcher#114]
_From @KylePDavis on March 3, 2015 13:57_

It would be great if double-clicking a paired token (bracket, brace, paren, quote, back-ticks, slash, etc.) selected to the other associated token, inclusively.

Here are a couple of examples of things that do this that I use frequently:
* `Terminal.app` in Mac OS X
* [ACE](https://github.com/ajaxorg/ace/) editor

_Copied from original issue: atom/atom#5817_

**Comment by fthebaud** [comment]
I agree, this would be a nice feature to have.

**Comment by Ajeet-Ganga** [comment]
The functionality you mentioned exist as package, but should have been core-feature. 
https://atom.io/packages/expand-selection-to-quotes 

Also I usually select large body of text to copy.
So  three clicks could be signal to copy.

Also I see my own behavior changes between programming files vs markdown. In programming files I rarely select/edit whole line, but in markdown/text I often select sentence.

So a configurable behavior based language type would be nice.

Optionally instead of making it configurable, we can associate it with 'Ctr + click' + click' for selection.

**Comment by 50Wliu** [comment]
As there is a community package that is providing this feature, I'm closing this for now unless there is significant justification that this should be provided by bracket-matcher and not a different package.

**Comment by akhilcb** [comment]
I tried expand-selection-to-quotes, but it is not working for me. It would be great if we could somehow map double click on a bracket to "Select Inside Brackets" + select both brackets. Something similar to Xcode selection on double tap of brackets. I couldn't find a community package for the same.

**Comment by chr1se** [comment]
has anyone found a package/solution to this?
double-clicking a brace to select/highlight enclosed-block
