### ISSUE TITLE
Problems with XML files and self-closed tags

### ISSUE THREAD

**Issue by Yajo** [atom/bracket-matcher#115]
Write this in an XML file:
```xml
<a>
    <b id="3">
        <c>
            <b id="1" />
            <b id="2" />
        </c>
    </b>
</a>
```
1. Put the caret inside b#2 or the closing tag of b#3. They highlight each other.
2. Put it just after the element b#1 or b#2 and press `ctrl-alt-.` It will try to close the self-closing element.
3. Undo step 2. Put the caret at the end of the file and press `ctrl-alt-.` 4 times. It will add some senseless `</b></c></b></a>`.

**Comment by andya9** [comment]
:+1:

**Comment by ttwd80** [comment]
it seems this only happens when there is a space.
for example, this same xml, without the attribute is completely legit.
```
<a>
    <b>
        <c>
            <b/>
            <b/>
        </c>
    </b>
</a>
```

however a single space
```
<a>
    <b>
        <c>
            <b />
            <b/>
        </c>
    </b>
</a>
```
a single space on line 4 from ```<b/>``` to ```<b />``` causes atom to misbehave. Spaces are needed for the xml attributes, so this also happens if the middle element has any attributes.

**Comment by schaeferto** [comment]
Ran in the same issue while writing xml files.
If a xml tag has properties and is self-closing it is not detected as "closed".
Is there any fix for this behaviour?

**Comment by 50Wliu** [comment]
Closing in favor of #203 - feel free to subscribe there for updates.
