### ISSUE TITLE
Closing tag with namespace prefix

### ISSUE THREAD

**Issue by ruv** [atom/bracket-matcher#217]
Any start-tag that contains a prefix is closed incorrectly.

For example,  `Ctrl+Alt+.` command after `<p:name>` produces `</p>`.

bracket-matcher version 0.79.0

**Comment by Platzer** [comment]
Hi i was not able to create a pull request: because apm install fails: [node-oniguruma
](https://github.com/atom/node-oniguruma/issues/9). So i had a look into the code, i think its in [tag-finder.coffee](https://github.com/atom/bracket-matcher/blob/master/lib/tag-finder.coffee) in line 134 function `tagsNotClosedInFragment`. I think a xml specification fulfilling regex would solve this one: 

`@parseFragment fragment, [], /<((?![0-9]|[xX][mM][lL])\w[-.:\w]*)|<\/((?![0-9]|[xX][mM][lL])\w[-.:\w]*)/, -> true`.

I hope this helps.

**Comment by MoritzKn** [comment]
In the mean time this was addressed by #229, however the regex used in this PR (`/<(\w[-\w]*(?:\:\w[-\w]*)?)|<\/(\w[-\w]*(?:\:\w[-\w]*)?)/`) is simpler and may leave out some cases.
