### ISSUE TITLE
Select all html tag

### ISSUE THREAD

**Issue by JackGarner** [atom/bracket-matcher#222]
hi all.
How to select all html tag with the both brackets by hotkey?
ctrl-alt-m select text only inside, but i need all tag. This feature is in pspad and very useful.
Example tag

```
<div>
text
sadsa
das
</div>
```

so, ctrl-alt-m return only 

```
text
sadsa
das
```

, i need after press hotkey

```
<div>
text
sadsa
das
</div>
```

**Comment by revelt** [comment]
I need this too. Please consider editing the title, this ticket is not even tagged as "enhancement", admins don't even understand what it means from the title.

"Select complete tag" maybe?

**Comment by 50Wliu** [comment]
So what this issue is asking for is a command to select the tags as well as the tag contents?

**Comment by revelt** [comment]
Exactly. Like `CTRL+CMD+M` but more than that, with opening and closing tag part.

On the original example code, I would place the cursor on the opening `<div>` and I'd get all of it selected, from `<div>` to `</div>`.

If you could trigger this when cursor is placed on closing tag (`</div>` in above example) — bonus points 👍

**Comment by akhilcb** [comment]
This would be a great improvement over current feature. Right now it is difficult to select the whole block to cut and paste it somewhere else. Current feature only selects inner part which limits the scope of this package. I am doing the selection manually now without using the shortcut key. Please let me know if anyone know any other way to do this right now.

**Comment by waknin** [comment]
Would also really appreciate this. +1

**Comment by revelt** [comment]
This issue is slightly muddy as there are no visuals are we're actually talking about two features.

## Issue 1. Fixing broken `ctrl-cmd-M`
Currently:
![current_situation](https://user-images.githubusercontent.com/8344688/30856004-e01c73e6-a2ae-11e7-8762-c8d78bee3cf6.gif)
Desired:
![current_situation_fixed](https://user-images.githubusercontent.com/8344688/30856011-e6d09406-a2ae-11e7-8fda-dc9eb921c914.gif)

Now, `ctrl-cmd-M` was originally meant for JS and it selects contents between brackets/curlies perfectly. It was not originally meant for HTML, hence this issue.

## Issue 2. New feature request – being able to select opening tag, its closing tag and all contents in-between (not only content between opening and closing tag)

![additional_feature](https://user-images.githubusercontent.com/8344688/30856054-04bbd9b2-a2af-11e7-8bcd-e52b58439e8b.gif)

---

So, the issue number two above is **different**, yet even more desired feature. It's similar to Dreamweaver's _Collapse Full Tag_ if some of you remember that. You were able to trigger collapsing by placing cursor anywhere on, right before or right after opening or closing tags. With collapsed piece you then could move/delete/cut/paste-over it.

Probably we should create a separate ticket for second feature, and leave this issue specifically for ctrl-cmd-M to be fixed on HTML. What do you guys think?

**Comment by Ben3eeE** [comment]
Issue 1 is already fixed and is currently scheduled to be released in Atom 1.22

**Comment by Ben3eeE** [comment]
@revelt Thank you for the graphics they really help out to understand the request :bowing_man: Do you want to open a new issue for issue 2 if that is a feature you want. Be sure to completely fill out the required issue template.

I am going to close this one out since it seems like we are mixing two different issues here and I'm not sure which one this issue is referring to.

**Comment by revelt** [comment]
Logical. I'll trawl the issues, maybe we already got something like this requested. Thanks for helping!

**Comment by akhilcb** [comment]
@revelt , Issue opened by @JackGarner was for Issue No:2 and not Issue No:1. Even your previous comment stated same. I am not sure what confused everyone after that. Please don't hijack threads and close it as there are people waiting for a fix for this.

**Comment by revelt** [comment]
@akhilcb you are right, issue "number one" is not released yet so maybe closing was a bit premature. At least it's coming soon..

**Comment by scooterlord** [comment]
Hello. Any progress on this one? I switched to Atom and it's probably the only thing I miss from my old editor.

**Comment by revelt** [comment]
Hi all, @scooterlord , I trawled through PR's and issues, apparently, Issue number 2 is being implemented in PR #74 and covered under issue #167 

Basically, you would click CMD+SHIFT+M once, select all content inside, then click **combo again** and get the opening/closing tags selected as well. This way you could "grow" the selection up until you reach the top of HTML tree.

It's a brilliant idea because we would not need to set/maintain/memorise a separate keyboard combo for "select tag with contents". You'd just press CMD+SHIFT+M twice. Or more, an even-number. That will be awesome.

**Comment by scooterlord** [comment]
@revelt When is it coming out??

**Comment by revelt** [comment]
@scooterlord I don't know, PR was submitted Oct 6, 2014 so it looks like it has stalled. I need it badly since I work with HTML, I hope it lands some time soon.

**Comment by dchatchet** [comment]
Chiming in, this "bubble up" selection would be immensely helpful. Just moved over permanently from Sublime and they have this behavior nailed. The hotkey selects the inside of the tag, then a second press selects the tags enclosing the content, and another press selects content of the outer tag, and so on. Sorry if thats not perfectly clear but this behavior is extremely helpful moving and selecting blocks of code.

**Comment by toddicus13** [comment]
Emmet has keybindings that expand/reduce selections to a tag which they call "balance outward/inward":

 - Balance (outward):  `ctrl-shift-E`
 - Balance (inward): `ctrl-shift-0`

Emmet for Atom docs: https://atom.io/packages/emmet
