### ISSUE TITLE
Still closing brackets although disabled

### ISSUE THREAD

**Issue by tobiasfielitz** [atom/bracket-matcher#321]
See screenshot.
![screen shot 2017-10-09 at 5 30 41 pm](https://user-images.githubusercontent.com/9712861/31326998-c588bdaa-ad17-11e7-88c0-5e99f6efbc0a.png)

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
