### ISSUE TITLE
Matching wrong elements with similar names

### ISSUE THREAD

**Issue by chescos** [atom/bracket-matcher#378]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The bracket matcher seems to match the wrong element if a child element contains the name of the parent.

### Steps to Reproduce

1. Copy the code below into an `.html` file
2. Move your cursor to the first line (`<v-element>`) and see which element gets matched

Code:

```
<v-element>
    <v-element-sub></v-element-sub>
</v-element>
```

**Expected behavior:** Match `<v-element>`with `</v-element>`

**Actual behavior:** Match `<v-element>` with `</v-element-sub>`

**Reproduces how often:** 100%

### Versions

```
Atom: 1.34.0
Electron: 2.0.16
Chrome: 61.0.3163.100
Node: 8.9.3
OS: Ubuntu 18.04
```

### Additional Information

Screenshot:

![selection_433](https://user-images.githubusercontent.com/12296880/51440740-70072a00-1cca-11e9-91af-256ffe465bf4.png)

**Comment by rsese** [comment]
Thanks for contributing!   I can reproduce with 1.34.0 on macOS 10.12.6 but this looks close enough to https://github.com/atom/bracket-matcher/issues/353 that we'll close as a duplicate for now (e.g. if I remove the `-` from the element name, the matching works).  You can subscribe to that issue if you'd like and if this ends up being a different issue, we can always reopen.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
