### ISSUE TITLE
XML tag matching does not work for similar named tag

### ISSUE THREAD

**Issue by BuZZ-dEE** [atom/bracket-matcher#388]
XML tag matching does not work for similarly named tags. See example below:

```xml
<mirrors>
  <mirror>
    <mirrorOf></mirrorOf>
  </mirror>
</mirrors>
```
![atom-xml-wrong-tag-matching](https://user-images.githubusercontent.com/125954/60609595-56622680-9dc2-11e9-96b0-366ff683d4f3.png)

**Comment by rsese** [comment]
Thanks for the report!

For future issues, please use the issue template as detailed below or your issues may be closed.

About the behavior you're seeing, it seems like another example of this issue I think (or at least related)?

https://github.com/atom/bracket-matcher/issues/353

We'll close in favor of that issue for now but we can reopen if it ends up being a different issue.

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
