### ISSUE TITLE
Pairing ' vs. "

### ISSUE THREAD

**Issue by bobrocke** [atom/bracket-matcher#86]
Atom is very smart about when it autocompletes pairs of ", but less so with '.

If the cursor is at the start or end of a word and you hit ", you get one " as you'd like.

If the cursor is at the end of a word and you hit ', you get one ', also as you'd like.

But if the cursor is at the start of a word and you hit ', you get '' and not what you'd want.

**Comment by izuzak** [comment]
Sorry for the delay in getting back to you on this and thanks for providing those examples. Those examples show that the package behaves the same way if you press `'` and `"` (paired quotes added before a non-word character). That sounds very similar to https://github.com/atom/bracket-matcher/issues/21 so I've added a comment there about this: https://github.com/atom/bracket-matcher/issues/21#issuecomment-141119538. 

I'm going to close this for now since we don't have an example of where the package is handling `'` and `"` differently. Let us know if you find one and I'd be happy to reopen.
